const emailRouteComponent = () => import('@/pages/apps/email/index.vue')

// 👉 Redirects
export const redirects = [
  // ℹ️ We are redirecting to different pages based on role.
  // NOTE: Role is just for UI purposes. ACL is based on abilities.
  {
    path: '/',
    name: 'index',
    redirect: to => {
      const userData = useCookie('userData')
      const accessToken = useCookie('accessToken')
      const refreshToken = useCookie('refreshToken')

      // If there is no active or refreshable session, always go to login
      const isLoggedIn = !!(userData.value && (accessToken.value || refreshToken.value))
      if (!isLoggedIn)
        return { name: 'login', query: to.query }

      const userRole = userData.value?.role?.toLowerCase()

      if (userRole === 'admin')
        return { name: 'dashboards-crm' }
      if (['sales_manager', 'sales_rep', 'warehouse_manager'].includes(userRole))
        return { name: 'dashboards-analytics' }

      return { name: 'login', query: to.query }
    },
  },
  {
    path: '/pages/user-profile',
    name: 'pages-user-profile',
    redirect: () => ({ name: 'pages-user-profile-tab', params: { tab: 'profile' } }),
  },
  {
    path: '/pages/account-settings',
    name: 'pages-account-settings',
    redirect: () => ({ name: 'pages-account-settings-tab', params: { tab: 'account' } }),
  },
]
export const routes = [
  // Email filter
  {
    path: '/apps/email/filter/:filter',
    name: 'apps-email-filter',
    component: emailRouteComponent,
    meta: {
      navActiveLink: 'apps-email',
      layoutWrapperClasses: 'layout-content-height-fixed',
    },
  },

  // Email label
  {
    path: '/apps/email/label/:label',
    name: 'apps-email-label',
    component: emailRouteComponent,
    meta: {
      // contentClass: 'email-application',
      navActiveLink: 'apps-email',
      layoutWrapperClasses: 'layout-content-height-fixed',
    },
  },
  {
    path: '/dashboards/logistics',
    name: 'dashboards-logistics',
    component: () => import('@/pages/apps/logistics/dashboard.vue'),
  },
  {
    path: '/dashboards/academy',
    name: 'dashboards-academy',
    component: () => import('@/pages/apps/academy/dashboard.vue'),
  },
  {
    path: '/apps/ecommerce/dashboard',
    name: 'apps-ecommerce-dashboard',
    component: () => import('@/pages/dashboards/ecommerce.vue'),
  },

  // ℹ️ The project directory name contains parentheses ("مجلد جديد (2)"), which
  // are glob special characters. unplugin-vue-router uses fast-glob internally
  // and silently fails to scan src/pages/products/, so the route is never
  // auto-generated. We register it manually here as a workaround — the manual
  // record replaces the (non-existent) auto-generated one, giving us one clean
  // registration with the correct name and component.
  {
    path: '/products',
    name: 'products',
    component: () => import('@/pages/products/index.vue'),
    meta: {
      action: 'read',
      subject: 'Auth',
    },
  },

  // ℹ️ Same parentheses workaround as products above — routes pages are not
  // auto-generated by unplugin-vue-router due to the glob issue.
  {
    path: '/routes',
    name: 'routes',
    component: () => import('@/pages/routes/index.vue'),
    meta: {
      action: 'read',
      subject: 'Auth',
    },
  },
  {
    path: '/routes/:id',
    name: 'routes-id',
    component: () => import('@/pages/routes/[id].vue'),
    meta: {
      action: 'read',
      subject: 'Auth',
      navActiveLink: 'routes',
    },
  },

  // ⚠️ Do NOT add manual routes for pages that already exist under `src/pages`
  // (e.g. /apps/territory/list, /apps/customer/list). unplugin-vue-router
  // generates them automatically, and a manual duplicate with the same name
  // makes vue-router drop the generated record — the path then resolves to an
  // orphaned layout route with no page component, so a hard refresh renders
  // a blank content area. Page meta belongs in `definePage()` inside the page.
]
