<script setup>
/**
 * Tracking Page
 *
 * Route name: tracking  →  /tracking
 *   Auto-generated by unplugin-vue-router from this file's location; the meta
 *   below is applied via definePage(). No manual entry in additional-routes.js —
 *   the glob-escaping fix in vite.config.js makes the scan work, so a manual
 *   duplicate would register the path twice.
 *
 * Thin wrapper; all UI lives in the TrackingDashboard view.
 */

definePage({
  meta: {
    // `manage Routes` is granted to ADMIN (manage all) and SALES_MANAGER only —
    // exactly the roles the tracking endpoints allow. See useAuth.updateAbility.
    action: 'manage',
    subject: 'Routes',
  },
})

import TrackingDashboard from '@/views/apps/logistics/tracking/TrackingDashboard.vue'
</script>

<template>
  <TrackingDashboard />
</template>
