<script setup>
/**
 * Routes List Page
 *
 * Route name: routes  →  /routes
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js — a manual
 * duplicate with the same name makes vue-router drop this auto-generated record.
 *
 * Thin wrapper; all UI lives in the RouteList view.
 */

definePage({
  meta: {
    action: 'read',
    subject: 'Auth',
  },
})

import RouteList from '@/views/apps/logistics/routes/RouteList.vue'
</script>

<template>
  <RouteList />
</template>
