/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-customer-list': RouteRecordInfo<'apps-customer-list', '/apps/customer/list', Record<never, never>, Record<never, never>>,
    'apps-invoice-list': RouteRecordInfo<'apps-invoice-list', '/apps/invoice/list', Record<never, never>, Record<never, never>>,
    'apps-invoice-preview-id': RouteRecordInfo<'apps-invoice-preview-id', '/apps/invoice/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-territory-list': RouteRecordInfo<'apps-territory-list', '/apps/territory/list', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'config': RouteRecordInfo<'config', '/config', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'demand-orders': RouteRecordInfo<'demand-orders', '/demand-orders', Record<never, never>, Record<never, never>>,
    'first-time-reset-password': RouteRecordInfo<'first-time-reset-password', '/first-time-reset-password', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'products': RouteRecordInfo<'products', '/products', Record<never, never>, Record<never, never>>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'return-sheets': RouteRecordInfo<'return-sheets', '/return-sheets', Record<never, never>, Record<never, never>>,
    'routes': RouteRecordInfo<'routes', '/routes', Record<never, never>, Record<never, never>>,
    'routes-id': RouteRecordInfo<'routes-id', '/routes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'stock-counts': RouteRecordInfo<'stock-counts', '/stock-counts', Record<never, never>, Record<never, never>>,
    'tracking': RouteRecordInfo<'tracking', '/tracking', Record<never, never>, Record<never, never>>,
    'van-inventory': RouteRecordInfo<'van-inventory', '/van-inventory', Record<never, never>, Record<never, never>>,
    'visits': RouteRecordInfo<'visits', '/visits', Record<never, never>, Record<never, never>>,
    'visits-id': RouteRecordInfo<'visits-id', '/visits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'warehouse-stock': RouteRecordInfo<'warehouse-stock', '/warehouse-stock', Record<never, never>, Record<never, never>>,
  }
}
