import { fileURLToPath } from 'node:url'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import VueI18nPlugin from '@intlify/unplugin-vue-i18n/vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { VueRouterAutoImports, getPascalCaseRouteName } from 'unplugin-vue-router'
import VueRouter from 'unplugin-vue-router/vite'
import { defineConfig, loadEnv } from 'vite'
import VueDevTools from 'vite-plugin-vue-devtools'
import MetaLayouts from 'vite-plugin-vue-meta-layouts'
import vuetify from 'vite-plugin-vuetify'
import svgLoader from 'vite-svg-loader'

// ℹ️ The project path contains parentheses ("مجلد جديد (2)"), which are glob
// pattern characters. unplugin-auto-import resolves relative `dirs` against the
// project root WITHOUT escaping them, so its directory scan silently matches
// nothing and auto-imports like `useCookie` break at runtime. We escape the
// parentheses as character classes ("[(]") so fast-glob treats them literally.
const projectRootDir = fileURLToPath(new URL('./', import.meta.url)).replace(/\\/g, '/')
const globSafePath = rel => (projectRootDir + rel).replace(/[()]/g, ch => `[${ch}]`)

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  // Load env variables so the Vite plugin can embed them in the SW config file.
  const env = loadEnv(mode, process.cwd(), 'VITE_')

  // ── Inline Firebase config Vite plugin ──────────────────────────────────────
  // Service workers cannot use import.meta.env (they are not Vite modules).
  // This plugin writes public/firebase-config.js at dev-start and build time
  // so that firebase-messaging-sw.js can importScripts() it and always have
  // the correct Firebase project config — even on a cold start with no open tab.
  //
  // The file contains ONLY public Web client configuration (no Admin credentials).
  const firebaseSwConfigPlugin = {
    name: 'firebase-sw-config',
    // Run during both build and dev server startup
    buildStart() {
      const config = {
        apiKey: env.VITE_FIREBASE_API_KEY ?? '',
        authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? '',
        projectId: env.VITE_FIREBASE_PROJECT_ID ?? '',
        storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET ?? '',
        messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? '',
        appId: env.VITE_FIREBASE_APP_ID ?? '',
        measurementId: env.VITE_FIREBASE_MEASUREMENT_ID ?? '',
      }

      // Write to public/ so Vite copies it to dist/ automatically.
      // The SW uses importScripts('/firebase-config.js') to load this.
      const outputPath = resolve(process.cwd(), 'public', 'firebase-config.js')
      const content = `// AUTO-GENERATED by vite.config.js — DO NOT EDIT MANUALLY\n// Re-generated on every \`npm run dev\` and \`npm run build\`.\n// Contains only public Firebase Web client configuration.\nself.FIREBASE_CONFIG = ${JSON.stringify(config, null, 2)}\n`

      writeFileSync(outputPath, content, 'utf-8')
    },
  }

return {
  plugins: [
    firebaseSwConfigPlugin,
    // Docs: https://github.com/posva/unplugin-vue-router
    // ℹ️ This plugin should be placed before vue plugin
    VueRouter({
      // ℹ️ The project path contains parentheses ("مجلد جديد (2)"), which are
      // glob special characters. unplugin-vue-router appends its own /**/*.vue
      // glob to routesFolder, so the option itself must be a plain filesystem
      // path (not a pre-escaped glob). We use fileURLToPath to get a literal
      // OS path; the plugin then escapes it internally before passing to
      // fast-glob, so parentheses are handled correctly.
      routesFolder: fileURLToPath(new URL('./src/pages', import.meta.url)),
      getRouteName: routeNode => {
        // Convert pascal case to kebab case
        return getPascalCaseRouteName(routeNode)
          .replace(/([a-z\d])([A-Z])/g, '$1-$2')
          .toLowerCase()
      },
      beforeWriteFiles: root => {
        root.insert('/apps/email/:filter', '/src/pages/apps/email/index.vue')
        root.insert('/apps/email/:label', '/src/pages/apps/email/index.vue')
      },
    }),
    vue({
      template: {
        compilerOptions: {
          isCustomElement: tag => tag === 'swiper-container' || tag === 'swiper-slide',
        },
      },
    }),
    VueDevTools(),
    vueJsx(),

    // Docs: https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin
    vuetify({
      styles: {
        configFile: 'src/assets/styles/variables/_vuetify.scss',
      },
    }),

    // Docs: https://github.com/dishait/vite-plugin-vue-meta-layouts?tab=readme-ov-file
    MetaLayouts({
      target: './src/layouts',
      defaultLayout: 'default',
    }),

    // Docs: https://github.com/antfu/unplugin-vue-components#unplugin-vue-components
    Components({
      // ℹ️ globSafePath: see note above — same parentheses issue as AutoImport
      dirs: [
        globSafePath('src/@core/components'),
        globSafePath('src/views/demos'),
        globSafePath('src/components'),
      ],
      dts: true,
      resolvers: [
        componentName => {
          // Auto import `VueApexCharts`
          if (componentName === 'VueApexCharts')
            return { name: 'default', from: 'vue3-apexcharts', as: 'VueApexCharts' }
        },
      ],
    }),

    // Docs: https://github.com/antfu/unplugin-auto-import#unplugin-auto-import
    AutoImport({
      imports: ['vue', VueRouterAutoImports, '@vueuse/core', '@vueuse/math', 'vue-i18n', 'pinia'],
      dirs: [
        globSafePath('src/@core/utils'),
        globSafePath('src/@core/composable/'),
        globSafePath('src/composables/'),
        globSafePath('src/utils/'),
        globSafePath('src/plugins/*/composables/*'),
      ],
      vueTemplate: true,

      // ℹ️ Disabled to avoid confusion & accidental usage
      ignore: ['useCookies', 'useStorage'],
      eslintrc: {
        enabled: true,
        filepath: './.eslintrc-auto-import.json',
      },
    }),

    // Docs: https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n#intlifyunplugin-vue-i18n
    VueI18nPlugin({
      runtimeOnly: true,
      compositionOnly: true,
      // ℹ️ globSafePath: see note above — same parentheses issue as AutoImport
      include: [
        globSafePath('src/plugins/i18n/locales/**'),
      ],
    }),
    svgLoader(),
  ],
  define: { 'process.env': {} },
  server: {
    port: 5173,
    proxy: {
      // Forward all /api requests to the Spring Boot backend during development.
      // This bypasses the browser CORS restriction — the request appears same-origin.
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        secure: false,
      },
    },
  },
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
      '@themeConfig': fileURLToPath(new URL('./themeConfig.js', import.meta.url)),
      '@core': fileURLToPath(new URL('./src/@core', import.meta.url)),
      '@layouts': fileURLToPath(new URL('./src/@layouts', import.meta.url)),
      '@images': fileURLToPath(new URL('./src/assets/images/', import.meta.url)),
      '@styles': fileURLToPath(new URL('./src/assets/styles/', import.meta.url)),
      '@configured-variables': fileURLToPath(new URL('./src/assets/styles/variables/_template.scss', import.meta.url)),
      '@db': fileURLToPath(new URL('./src/plugins/fake-api/handlers/', import.meta.url)),
      '@api-utils': fileURLToPath(new URL('./src/plugins/fake-api/utils/', import.meta.url)),
    },
  },
  build: {
    chunkSizeWarningLimit: 5000,
  },
  optimizeDeps: {
    exclude: ['vuetify'],
    entries: [
      './src/**/*.vue',
    ],
  },
}
}) // end defineConfig
