<script setup>
/**
 * Warehouse Stock List Page
 *
 * Route name: warehouse-stock  →  /warehouse-stock
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js — a manual
 * duplicate with the same name makes vue-router drop this auto-generated record,
 * leaving an orphaned component-less route that renders blank on hard refresh.
 *
 * This page is a thin wrapper; all UI lives in the WarehouseStockList view so the
 * component can be reused/tested independently of routing.
 *
 * Access rules:
 *   - All authenticated roles can VIEW the list (action: 'read', subject: 'Auth')
 *   - Only ADMIN can Receive / Correct stock (guarded inside the view via useAuth)
 */

definePage({
  meta: {
    action: 'read',
    subject: 'Auth',
  },
})

import WarehouseStockList from '@/views/apps/warehouse-stock/WarehouseStockList.vue'
</script>

<template>
  <WarehouseStockList />
</template>
