<script setup>
/**
 * Stock Counts Page
 *
 * Route name: stock-counts  →  /stock-counts
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js — a manual
 * duplicate with the same name makes vue-router drop this auto-generated record,
 * leaving an orphaned component-less route that renders blank on hard refresh.
 *
 * Thin wrapper; all UI lives in the StockCountList view.
 *
 * Access rules — the read and write halves differ, which is why this page is
 * NOT gated on `manage: Warehouse` like Warehouse Stock is:
 *   - ADMIN, WAREHOUSE_MANAGER and SALES_MANAGER can all reach the page, since
 *     GET /stock-counts and GET /stock-counts/{id} admit all three.
 *   - Creating, editing lines and finalizing are ADMIN + WAREHOUSE_MANAGER
 *     only. SALES_MANAGER therefore sees a read-only page; that half is guarded
 *     inside the view via useAuth.
 */

definePage({
  meta: {
    action: 'read',
    subject: 'StockCounts',
  },
})

import StockCountList from '@/views/apps/stock-count/StockCountList.vue'
</script>

<template>
  <StockCountList />
</template>
