<script setup>
/**
 * Stock Counts Page
 *
 * Route name: stock-counts  →  /stock-counts
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js — a manual
 * duplicate with the same name makes vue-router drop this auto-generated record,
 * leaving an orphaned component-less route that renders blank on hard refresh.
 *
 * Thin wrapper; all UI lives in the StockCountList view.
 *
 * Access rules:
 *   - Only ADMIN and WAREHOUSE_MANAGER can reach this page — same gate as
 *     Warehouse Stock, since a stock count writes to the same inventory.
 *   - The mutating actions (create / edit lines / finalize) are additionally
 *     guarded inside the view via useAuth.
 */

definePage({
  meta: {
    action: 'manage',
    subject: 'Warehouse',
  },
})

import StockCountList from '@/views/apps/stock-count/StockCountList.vue'
</script>

<template>
  <StockCountList />
</template>
