<script setup>
/**
 * Return Sheets Page
 *
 * Route name: return-sheets  →  /return-sheets
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js.
 *
 * Thin wrapper; all UI lives in the ReturnSheetList view.
 */

definePage({
  meta: {
    action: 'read',
    subject: 'Management',
  },
})

import ReturnSheetList from '@/views/apps/logistics/return-sheets/ReturnSheetList.vue'
</script>

<template>
  <ReturnSheetList />
</template>
