<script setup>
/**
 * Van Inventory Page
 *
 * Route name: van-inventory  →  /van-inventory
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js.
 *
 * Thin wrapper; all UI lives in the VanInventory view.
 */

definePage({
  meta: {
    action: 'read',
    subject: 'Auth',
  },
})

import VanInventory from '@/views/apps/logistics/van-inventory/VanInventory.vue'
</script>

<template>
  <VanInventory />
</template>
