<script setup>
/**
 * Product List Page
 *
 * Route name: products  →  /products   (auto-generated by unplugin-vue-router)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js — a manual
 * duplicate with the same name makes vue-router drop this auto-generated record,
 * leaving an orphaned component-less route that renders blank on hard refresh.
 *
 * Access rules:
 *   - All authenticated roles can VIEW the list (action: 'read', subject: 'Auth')
 *   - Only ADMIN can CREATE / EDIT / DELETE / change status (checked via useAuth)
 */

definePage({
  meta: {
    action: 'read',
    subject: 'Auth',
  },
})

import ProductFormDrawer from '@/views/apps/product/ProductFormDrawer.vue'
import {
  useProducts,
  PRODUCT_STATUSES,
  resolveStatusVariant,
} from '@/composables/useProducts'
import { useAuth } from '@/composables/useAuth'

// ── Auth — role guard for mutating actions ───────────────────────────────────
const { userData } = useAuth()
const isAdmin = computed(() => userData.value?.role?.toLowerCase() === 'admin')

// ── Composable ────────────────────────────────────────────────────────────────
const {
  products,
  totalProducts,
  isListLoading,
  listError,
  searchQuery,
  selectedStatus,
  page,
  itemsPerPage,
  updateOptions,
  editingProduct,
  isDetailLoading,
  isSubmitting,
  snackbar,
  fetchAllProducts,
  fetchProduct,
  createProduct,
  updateProduct,
  changeProductStatus,
  deleteProduct,
  clearEditing,
} = useProducts()

// ── Table Headers ──────────────────────────────────────────────────────────────
const headers = [
  { title: 'Product',    key: 'name',          sortable: true  },
  { title: 'SKU',        key: 'sku',           sortable: true  },
  { title: 'Barcode',    key: 'barcode',       sortable: false },
  { title: 'Price',      key: 'price',         sortable: true  },
  { title: 'Unit',       key: 'unitOfMeasure', sortable: false },
  { title: 'Min Stock',  key: 'minStockLevel', sortable: true  },
  { title: 'Status',     key: 'status',        sortable: true  },
  { title: 'Actions',    key: 'actions',       sortable: false, align: 'end' },
]

// ── Drawer State ───────────────────────────────────────────────────────────────
const isDrawerOpen = ref(false)

// ── Delete Confirmation Dialog State ──────────────────────────────────────────
const isDeleteDialogOpen = ref(false)
const productToDelete    = ref(null)   // { id, name } of the row pending deletion

// ── Handlers ───────────────────────────────────────────────────────────────────

/** Open drawer in CREATE mode */
const openCreate = () => {
  clearEditing()
  isDrawerOpen.value = true
}

/** Open drawer in EDIT mode — fetch the latest data first */
const openEdit = async product => {
  isDrawerOpen.value = true
  await fetchProduct(product.id)
}

/** Unified submit from drawer — create or update based on mode */
const onSubmit = async ({ id, ...payload }) => {
  const result = id
    ? await updateProduct(id, payload)
    : await createProduct(payload)

  if (result.success) {
    isDrawerOpen.value = false
    clearEditing()
  }
}

/** Close drawer and clear edit state */
const onDrawerClose = () => {
  isDrawerOpen.value = false
  clearEditing()
}

/** Inline status toggle from the row menu */
const onChangeStatus = async (product, newStatus) => {
  await changeProductStatus(product.id, newStatus)
}

/** Show delete confirmation dialog */
const onDelete = product => {
  productToDelete.value    = product
  isDeleteDialogOpen.value = true
}

/** Confirmed delete — fires the DELETE API call */
const onConfirmDelete = async () => {
  if (!productToDelete.value) return
  isDeleteDialogOpen.value = false
  await deleteProduct(productToDelete.value.id)
  productToDelete.value = null
}

/** Cancel delete dialog */
const onCancelDelete = () => {
  isDeleteDialogOpen.value = false
  productToDelete.value    = null
}

// ── Price formatter ─────────────────────────────────────────────────────────────
const formatPrice = value => {
  if (value === null || value === undefined) return '—'

  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(value)
}

// ── Fetch on mount ─────────────────────────────────────────────────────────────
onMounted(fetchAllProducts)
</script>

<template>
  <section>
    <!-- ── Summary Widget ──────────────────────────────────────────────────── -->
    <VRow class="mb-6">
      <VCol
        cols="12"
        sm="6"
        md="3"
      >
        <VCard>
          <VCardText class="d-flex justify-space-between align-center">
            <div>
              <div class="text-body-2 text-medium-emphasis mb-1">
                Total Products
              </div>
              <h4 class="text-h4">
                {{ totalProducts }}
              </h4>
            </div>
            <VAvatar
              color="primary"
              variant="tonal"
              rounded
              size="44"
            >
              <VIcon
                icon="tabler-packages"
                size="26"
              />
            </VAvatar>
          </VCardText>
        </VCard>
      </VCol>
    </VRow>

    <!-- ── Main Card ─────────────────────────────────────────────────────────── -->
    <VCard>
      <VCardItem class="pb-2">
        <VCardTitle>Product Management</VCardTitle>
      </VCardItem>

      <!-- Filters -->
      <VCardText>
        <VRow>
          <!-- Search -->
          <VCol
            cols="12"
            sm="8"
          >
            <AppTextField
              v-model="searchQuery"
              placeholder="Search by name, SKU or barcode…"
              prepend-inner-icon="tabler-search"
              clearable
              @click:clear="searchQuery = ''"
            />
          </VCol>

          <!-- Status filter -->
          <VCol
            cols="12"
            sm="4"
          >
            <AppSelect
              v-model="selectedStatus"
              placeholder="Filter by Status"
              :items="PRODUCT_STATUSES"
              item-title="title"
              item-value="value"
              clearable
              clear-icon="tabler-x"
            />
          </VCol>
        </VRow>
      </VCardText>

      <VDivider />

      <!-- Toolbar -->
      <VCardText class="d-flex flex-wrap align-center gap-4">
        <!-- Items per page -->
        <AppSelect
          :model-value="itemsPerPage"
          :items="[
            { value: 10, title: '10' },
            { value: 25, title: '25' },
            { value: 50, title: '50' },
          ]"
          style="inline-size: 6.25rem;"
          @update:model-value="itemsPerPage = parseInt($event, 10)"
        />

        <VSpacer />

        <!-- Add Product — Admin only -->
        <VBtn
          v-if="isAdmin"
          prepend-icon="tabler-plus"
          @click="openCreate"
        >
          Add Product
        </VBtn>
      </VCardText>

      <VDivider />

      <!-- Error state -->
      <VAlert
        v-if="listError"
        type="error"
        variant="tonal"
        class="ma-4"
        closable
      >
        {{ listError }}
      </VAlert>

      <!--
        VDataTableServer — server-side pagination + sorting.
        @update:options forwards sort changes to the composable.
        We disable the built-in footer and render our own TablePagination.
      -->
      <VDataTableServer
        :headers="headers"
        :items="products"
        :items-length="totalProducts"
        :loading="isListLoading"
        :page="page"
        :items-per-page="itemsPerPage"
        item-value="id"
        class="text-no-wrap"
        hide-default-footer
        @update:options="updateOptions"
      >
        <!-- Loading -->
        <template #loading>
          <VSkeletonLoader type="table-row@8" />
        </template>

        <!-- Empty -->
        <template #no-data>
          <div class="d-flex flex-column align-center justify-center py-10 gap-3">
            <VIcon
              icon="tabler-package-off"
              size="48"
              color="secondary"
            />
            <p class="text-body-1 text-medium-emphasis mb-0">
              <template v-if="searchQuery || selectedStatus">
                No products match your filters.
              </template>
              <template v-else>
                No products found.
                <span v-if="isAdmin">Create your first product to get started.</span>
              </template>
            </p>
            <VBtn
              v-if="isAdmin && !searchQuery && !selectedStatus"
              prepend-icon="tabler-plus"
              size="small"
              @click="openCreate"
            >
              Add Product
            </VBtn>
          </div>
        </template>

        <!-- Product (name) column -->
        <template #item.name="{ item }">
          <div class="d-flex align-center gap-x-3">
            <VAvatar
              size="36"
              color="primary"
              variant="tonal"
            >
              <VIcon
                icon="tabler-box"
                size="18"
              />
            </VAvatar>
            <span class="text-body-1 font-weight-medium text-high-emphasis">
              {{ item.name }}
            </span>
          </div>
        </template>

        <!-- SKU column -->
        <template #item.sku="{ item }">
          <span class="text-body-2 font-weight-medium">{{ item.sku || '—' }}</span>
        </template>

        <!-- Barcode column -->
        <template #item.barcode="{ item }">
          <span class="text-body-2 text-medium-emphasis">{{ item.barcode || '—' }}</span>
        </template>

        <!-- Price column -->
        <template #item.price="{ item }">
          <span class="text-body-2 font-weight-medium">{{ formatPrice(item.price) }}</span>
        </template>

        <!-- Unit column -->
        <template #item.unitOfMeasure="{ item }">
          <span class="text-body-2 text-capitalize">
            {{ item.unitOfMeasure?.toLowerCase() ?? '—' }}
          </span>
        </template>

        <!-- Min Stock column -->
        <template #item.minStockLevel="{ item }">
          <span class="text-body-2">{{ item.minStockLevel ?? '—' }}</span>
        </template>

        <!-- Status column -->
        <template #item.status="{ item }">
          <VChip
            :color="resolveStatusVariant(item.status)"
            size="small"
            label
            class="text-capitalize"
          >
            {{ item.status?.toLowerCase() ?? '—' }}
          </VChip>
        </template>

        <!-- Actions column -->
        <template #item.actions="{ item }">
          <div class="d-flex justify-end gap-1">
            <!-- Edit — Admin only -->
            <VTooltip
              v-if="isAdmin"
              text="Edit Product"
            >
              <template #activator="{ props: tp }">
                <IconBtn
                  v-bind="tp"
                  :loading="isDetailLoading"
                  @click="openEdit(item)"
                >
                  <VIcon icon="tabler-edit" />
                </IconBtn>
              </template>
            </VTooltip>

            <!-- Status / Delete menu — Admin only -->
            <VBtn
              v-if="isAdmin"
              icon
              variant="text"
              color="medium-emphasis"
              size="small"
            >
              <VIcon icon="tabler-dots-vertical" />
              <VMenu activator="parent">
                <VList density="compact">
                  <!-- Change status options (all but the current one) -->
                  <VListItem
                    v-for="s in PRODUCT_STATUSES.filter(st => st.value !== item.status)"
                    :key="s.value"
                    @click="onChangeStatus(item, s.value)"
                  >
                    <template #prepend>
                      <VIcon
                        :icon="s.value === 'ACTIVE' ? 'tabler-circle-check' : 'tabler-circle-x'"
                        :color="resolveStatusVariant(s.value)"
                        size="16"
                      />
                    </template>
                    <VListItemTitle>Set {{ s.title }}</VListItemTitle>
                  </VListItem>

                  <VDivider class="my-1" />

                  <!-- Delete -->
                  <VListItem @click="onDelete(item)">
                    <template #prepend>
                      <VIcon
                        icon="tabler-trash"
                        color="error"
                        size="16"
                      />
                    </template>
                    <VListItemTitle class="text-error">
                      Delete
                    </VListItemTitle>
                  </VListItem>
                </VList>
              </VMenu>
            </VBtn>

            <!-- Non-admin: read-only indicator -->
            <VChip
              v-if="!isAdmin"
              size="small"
              color="secondary"
              variant="tonal"
              label
            >
              View only
            </VChip>
          </div>
        </template>

        <!-- Pagination footer -->
        <template #bottom>
          <TablePagination
            v-model:page="page"
            :items-per-page="itemsPerPage"
            :total-items="totalProducts"
          />
        </template>
      </VDataTableServer>
    </VCard>

    <!-- ── Product Form Drawer (Create / Edit) ─────────────────────────────── -->
    <ProductFormDrawer
      v-model:is-drawer-open="isDrawerOpen"
      :product="editingProduct"
      :is-submitting="isSubmitting"
      @submit="onSubmit"
      @update:is-drawer-open="val => { if (!val) onDrawerClose() }"
    />

    <!-- ── Delete Confirmation Dialog ──────────────────────────────────────── -->
    <VDialog
      v-model="isDeleteDialogOpen"
      max-width="440"
      persistent
    >
      <VCard>
        <VCardTitle class="d-flex align-center gap-2 pa-4">
          <VIcon
            icon="tabler-alert-triangle"
            color="error"
            size="24"
          />
          Delete Product
        </VCardTitle>

        <VDivider />

        <VCardText class="pa-4">
          <p class="mb-1">
            Are you sure you want to delete
            <strong>{{ productToDelete?.name }}</strong>?
          </p>
          <p class="text-medium-emphasis text-body-2 mb-0">
            This action cannot be undone.
          </p>
        </VCardText>

        <VCardActions class="pa-4 pt-0 gap-2 justify-end">
          <VBtn
            variant="tonal"
            color="secondary"
            :disabled="isSubmitting"
            @click="onCancelDelete"
          >
            Cancel
          </VBtn>
          <VBtn
            color="error"
            :loading="isSubmitting"
            @click="onConfirmDelete"
          >
            <VIcon
              icon="tabler-trash"
              start
            />
            Delete
          </VBtn>
        </VCardActions>
      </VCard>
    </VDialog>

    <!-- ── Global Snackbar ─────────────────────────────────────────────────── -->
    <VSnackbar
      v-model="snackbar.show"
      :color="snackbar.color"
      :timeout="3500"
      location="bottom end"
    >
      <VIcon
        :icon="snackbar.color === 'success' ? 'tabler-circle-check' : 'tabler-alert-circle'"
        class="me-2"
      />
      {{ snackbar.message }}
    </VSnackbar>
  </section>
</template>
