<script setup>
/**
 * Demand Orders Page
 *
 * Route name: demand-orders  →  /demand-orders
 *   (auto-generated by unplugin-vue-router from this file's path)
 *
 * ⚠️ Do NOT also register this route manually in additional-routes.js — a manual
 * duplicate with the same name makes vue-router drop this auto-generated record.
 *
 * Thin wrapper; all UI lives in the DemandOrderList view.
 */

definePage({
  meta: {
    action: 'read',
    subject: 'Auth',
  },
})

import DemandOrderList from '@/views/apps/logistics/demand-orders/DemandOrderList.vue'
</script>

<template>
  <DemandOrderList />
</template>
